# Generated by Django 4.2.1 on 2023-06-04 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('video', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Subtitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.FileField(upload_to='media/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.video')),
            ],
        ),
    ]
